version: '3.1'

networks:
  test_network:
services:
  db:
    image: postgres:14
    container_name: postgre14-db
    ports:
      - "5432:5432"
    networks:
      - test_network
    restart: always
    volumes:
      - ./postgres_data.sql:/docker-entrypoint-initdb.d/postgres_data.sql
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080